### ISSUE TITLE
Can you please change hardcoded menu values to higher values?

### ISSUE THREAD

**Issue by danb1974** [flode/SetAndroidProcessLimit#1]
I want to set the process limit to higher values, so menu entries like 1, 2, 5, 10, 20, 50, 100 would be very helpful instead of 1, 2, 3, 4, 5, 6, 7 (as modern phones tend to have 2 or 3GB of ram). The phone already has an option to limit them to 1, 2, 3 or 4.

**Comment by tvierling** [comment]
Well, part of the purpose of this app is to provide a non-default limit for devices which are particularly memory constrained. If you have multiple GB of RAM, you're better off not using this app at all, and letting Android manage what apps stay cached automatically.

**Comment by flode** [comment]
I think tvierling is right, it probably won't be much of an improvment for you. If you want to try you can easily change the values here:
https://github.com/flode/SetAndroidProcessLimit/blob/master/app/src/main/res/values/strings_activity_set_process_limit.xml
Just add some additional options there.

**Comment by danb1974** [comment]
My phone keeps evicting inactive applications from memory, despite showing all the time that I have at least 900MB of free ram. I just learned how to recompile and self-sign the application (btw, had to bump minSdkVersion from 13 to 14 to fix a lint error), so I have now a custom version with bigger values. I though maybe it would help others too if you include bigger values in your application.

Without setting the limit, I was not able to get past 13 inactive cached apps, each time I started a new one, another one was evicted.

Also, if you can tell me if android does evict inactive apps by other criteria then free memory (which I have plenty, and minfree is set at 120MB), it's really annoying to see apps reloading, even if it only takes a second.

Thanks.

**Comment by flode** [comment]
Ok this makes sense, I'll some higher values as well. I don't know how android decides to kill apps either.

**Comment by tvierling** [comment]
Actually, once you're over 1GiB RAM, it really is better to let Android regulate the number of cached-state background processes. Setting it extremely high (assuming Android will even heed a higher number) will actually _hurt_ your performance because you're trying to force idle apps to stay in memory at the cost of reducing the available memory for Linux's page cache.

Cache memory is far more important than keeping a really large number of Dalvik VMs in memory. If an app gets evicted on a device with enough memory, its data and dexcode are actually still in memory in page cache. "Restarting" the idle apps takes a lot less time than you think, and actually uses _less_ battery because RAM is already populated; the OS doesn't have to reload those pages from flash memory. This is how Linux's memory manager is designed and it works extremely well when you have memory to spare.

If you have enough memory that Android is _not_ keeping it mostly full of idle apps with the default settings, then let the system use the Linux page cache as it was intended to be used. Your CPU and battery will thank you.

**Comment by danb1974** [comment]
But my phone has plenty of free (as in unused, not buffer, not cached) ram:

<pre>Total RAM: 2016644 kB
 Free RAM: 883420 kB (230000 cached pss + 131652 cached + 521768 free)
 Used RAM: 852001 kB (805401 used pss + 1684 buffers + 8972 shmem + 35944 slab)
 Lost RAM: 281223 kB
     ZRAM: 4 kB physical used for 0 kB in swap (0 kB total swap)
   Tuning: 256 (large 512), oom 122880 kB, restore limit 40960 kB (high-end-gfx)</pre>

See? 0.5GB free and yet evicting cached inactive applications - which now only have a saved stated, but are no longer in memory (shown in task manager with 0.00b) and at next access will be reloaded from flash, and take 0.5 - 1 second to do that, instead of instant resume from ram

**Comment by danb1974** [comment]
A few notes/questions, after more fiddling around the processlimit thing...

1) You should write in big bold letters the installing instructions (the "copy to /system/priv-app" part), dumb user (that's me) just clicks on app, app goes to /system/app and does not work. Because dumb user did not know that set process limit permission is not working for user apps.

2) App does not output an error if it cannot set process limit (due to dumb user above, for instance). Dumb user had to use logcat to find out

3) Not sure at which point this limit is set at boot, I still get a few kills (hitting 17 empty processes) right after phone startup. Before I would get dozens of kills (making me wonder, isn't that really stupid, starting then killing so many processes because of the hardcoded limit?)

4) I tried to modify services.jar (where the initial limit of MAX_CACHED_APPS = 24 is set, from which empty and cached limits are calculated as 2/3 and 1/3 of that value). I unpacked the jar, used backsmali to decompile classes.dex, modified the limit, recompiled, repacked services.jar, replaced on the phone, rebooted, rebuild dalvik cache. But it had no effect. What have I missed?

Sorry for being so insistent, not familiar with android and trying to understand.

Thank you

**Comment by flode** [comment]
I added the message for dumb users. I don't really know what happens on android boot either, sorry.
